//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> stock { get; set; }
        public string isbn { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public Nullable<int> page { get; set; }
        public string cover_page_picture { get; set; }
    }
}
